---
name: String-Random
version: 0.22
author:
  - 'Steven Pritchard <steve@silug.org>'
abstract: Perl module to generate random strings based on a pattern
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  String::Random:
    file: lib/String/Random.pm
    version: 0.22
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
